name: Joey Phinn
favicon: null
layout_spectrum: 0.43871
typography_spectrum: 0.01352
title: Princeling
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#adacb1'
    - '#2d2c28'
    - '#877f7c'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
